import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { MemberProvider } from "./members/MemberProvider";
import MemberNav from "./members/MemberNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MemberProvider>
          <header className="flex items-center justify-between px-8 py-3 border-b border-gray-200">
            <Link href="/dogs" className="text-lg font-bold">
              Demo Dog
            </Link>
            <MemberNav />
          </header>
          {children}
        </MemberProvider>
      </body>
    </html>
  );
}
